# Generated by Django 4.1.5 on 2023-01-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_categoriasmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriasmodel',
            name='producto',
        ),
        migrations.CreateModel(
            name='ProductosCategoriasModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.categoriasmodel')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.productosmodel')),
            ],
            options={
                'db_table': 'productos_categorias',
            },
        ),
    ]
