"""campo estado

Revision ID: 313e1796c412
Revises: 5a790c38c2c1
Create Date: 2023-01-19 21:53:36.435667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313e1796c412'
down_revision = '5a790c38c2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
